name: CI
on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:

jobs:
  tox:
    name: ${{ matrix.name }}
    runs-on: ubuntu-latest

    container: python:${{ matrix.python }}

    strategy:
      fail-fast: false
      matrix:
        include:
          - {name: '3.13', python: '3.13', tox: py313}
          - {name: '3.12', python: '3.12', tox: py312}
          - {name: '3.11', python: '3.11', tox: py311}
          - {name: '3.10', python: '3.10', tox: py310}
          - {name: '3.9', python: '3.9', tox: py39}
          - {name: 'format', python: '3.13', tox: format}
          - {name: 'mypy', python: '3.13', tox: mypy}
          - {name: 'pep8', python: '3.13', tox: pep8}
          - {name: 'package', python: '3.13', tox: package}
          - {name: 'docs', python: '3.13', tox: docs}

    steps:
      - uses: pgjones/actions/tox@95d55ce685019891495ca3470a25ce533920aeb0
        with:
          environment: ${{ matrix.tox }}
